[package]
name = "mythra"
version = "0.1.0"
authors = ["Diretnan Domnan <diretnandomnan@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.0.0-beta.2", features = ["yaml"] }
serde = { version = "1.0.101", features = ["derive"] }
reqwest = { version = "0.10", features = ["blocking", "json"] }
serde_json = "1.0.40"
