name: Deploy to GCP

on:
  release:
    types: [ released, edited ]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.OPENSSL_KEY }}
          host: ${{ secrets.GCP_HOST }}
          username: ${{secrets.USERNAME}}
          script: |
            cd /home/${{secrets.USERNAME}}/mythra
            git pull -f
            tag=`git tag | tail -n 1`
            curl https://github.com/deven96/mythra/releases/download/$tag/mythra-ubuntu-latest-$tag > mythra
            chmod u+x ./mythra
            # kill previous running ports
            sudo lsof -ti tcp:${{secrets.MYTHRA_PORT}} | sudo xargs kill -9
            sudo lsof -ti tcp:${{secrets.CHROMEDRIVER_PORT}} |sudo  xargs kill -9
            chromedriver --port=${{secrets.CHROMEDRIVER_PORT}} --log-level=DEBUG &
            ./mythra api --port ${{secrets.MYTHRA_PORT}} --verbose debug &

