name: Deploy to Heroku

on:
  push:
    tags: v[1-9]+.[0-9]+.[0-9]+

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.6.8 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "gophie-mythra" #Must be unique in Heroku
          heroku_email: "gophiemythra@gmail.com"
