name: Release to GitHub

on:
  push:
    tags: 
      - 'v*'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v2
      - run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - run: |
              if [ "$CURRENT_OS" == "ubuntu-18.04" ]; then
                sudo apt-get install libncursesw5-dev
              elif [ "$CURRENT_OS" == "macos-latest" ]; then
                brew install ncurses
              fi
              sed -i 's/version:.*/version: "${{env.RELEASE_VERSION}}"/g' src/cli.yaml
        env:
          CURRENT_OS: ${{matrix.os}}
      - run:  cargo build --release --locked && chmod +x target/release/mythra
      - uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{secrets.GITHUB_TOKEN}}
          file: target/release/mythra
          asset_name: mythra-${{matrix.os}}-${{env.RELEASE_VERSION}}
          tag: ${{env.RELEASE_VERSION}}
          overwrite: true
