name: Deploy docs to Stoplight

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - run: npm install -g @stoplight/cli@3.0.1
      - run: sed -i "1s/.*/${{secrets.REPLACE}}/" $(npm config get prefix)/lib/node_modules/@stoplight/cli/bin/stoplight.js
      - run: $(npm config get prefix)/bin/stoplight publish --token ${{secrets.STOPLIGHT_TOKEN}} --url https://stoplight.io/api
